eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9102/eureka/
server:
    port: 8888

spring:
    datasource:
        initialization-mode: always
        url: jdbc:postgresql://localhost:5432/medipractice
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true

    redis:
        database: 1
        host: 192.168.0.12
        password: ''
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0


oauth2:
    client:
        id: versusmind
        secret: $2a$04$kb4dXtrYH36C/55P0QBEcu9QGtOqUniXB.Kp2pcYaSZdOfrTBeqvO